"""add_stock_daily_report_shipment_adjustment

Revision ID: 55b9d1537055
Revises: 20260528_seed_default_company
Create Date: 2026-05-28 03:53:57.213491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b9d1537055'
down_revision: Union[str, None] = '20260528_seed_default_company'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
