"""init

Revision ID: 74f41388fa41
Revises: 
Create Date: 2026-05-27 21:23:15.732501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74f41388fa41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_username', sa.String(length=100), nullable=False),
    sa.Column('actor_full_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_display', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_company_id'), 'audit_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('adjustment_number_sequences',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'year')
    )
    op.create_table('count_catalog',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('count_value', sa.String(length=50), nullable=False),
    sa.Column('yarn_type', sa.String(length=100), nullable=True),
    sa.Column('composition', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'count_value', name='uq_count_company_value')
    )
    op.create_index(op.f('ix_count_catalog_company_id'), 'count_catalog', ['company_id'], unique=False)
    op.create_table('counterparties',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('counterparty_type', sa.Enum('BUYER', 'TOLLING_OWNER', 'BOTH', name='counterpartytype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'tax_id', name='uq_counterparty_company_tax')
    )
    op.create_index(op.f('ix_counterparties_company_id'), 'counterparties', ['company_id'], unique=False)
    op.create_table('lot_number_sequences',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('last_sequence', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'year')
    )
    op.create_table('lots',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.String(length=20), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('sequence_number', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'BLOCKED', name='lotstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('auto_closed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'lot_number', name='uq_lot_company_number'),
    sa.UniqueConstraint('company_id', 'year', 'sequence_number', name='uq_lot_company_year_seq')
    )
    op.create_index(op.f('ix_lots_company_id'), 'lots', ['company_id'], unique=False)
    op.create_table('shipment_number_sequences',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('year_month', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'year_month')
    )
    op.create_table('warehouses',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('warehouse_type', sa.Enum('RAW_COTTON', 'FINISHED_GOODS', 'WASTE', 'PACKAGING', name='warehousetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_warehouse_company_code')
    )
    op.create_index(op.f('ix_warehouses_company_id'), 'warehouses', ['company_id'], unique=False)
    op.create_table('contracts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'contract_number', name='uq_contract_company_number')
    )
    op.create_index(op.f('ix_contracts_company_id'), 'contracts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contracts_counterparty_id'), 'contracts', ['counterparty_id'], unique=False)
    op.create_table('counterparty_contacts',
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_value', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparty_contacts_counterparty_id'), 'counterparty_contacts', ['counterparty_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'CLOSED', name='reportstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('last_reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reopened_by', sa.UUID(), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('reopen_count', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'warehouse_id', 'report_date', name='uq_daily_report_company_warehouse_date')
    )
    op.create_index('idx_dr_warehouse_date', 'daily_reports', ['company_id', 'warehouse_id', 'report_date'], unique=False)
    op.create_index(op.f('ix_daily_reports_company_id'), 'daily_reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_daily_reports_warehouse_id'), 'daily_reports', ['warehouse_id'], unique=False)
    op.create_table('inventory_adjustments',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_number', sa.String(length=20), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', name='adjustmentstatus'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'adjustment_number', name='uq_adj_company_number')
    )
    op.create_index(op.f('ix_inventory_adjustments_company_id'), 'inventory_adjustments', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_warehouse_id'), 'inventory_adjustments', ['warehouse_id'], unique=False)
    op.create_table('stock_transactions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('count_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('waste_type', sa.Enum('ST_3', 'ST_7_11', 'ST_1', 'ST_36', 'ST_98', 'MYCHKA', 'ROVNITSA', name='wastetype'), nullable=True),
    sa.Column('pkg_item_type', sa.Enum('BAG', 'CONE', 'PACKAGE', 'CORRUGATED_SHEET', 'PARAFFIN', 'BOX', name='packagingitemtype'), nullable=True),
    sa.Column('transaction_type', sa.Enum('OPENING_BALANCE', 'OPENING_BALANCE_CORRECTION', 'PRODUCTION_INBOUND', 'PRODUCTION_ISSUE', 'RECEIPT', 'SHIPMENT_OUTBOUND', 'SHIPMENT_CANCEL_REVERSAL', 'WASTE_INBOUND', 'WASTE_SALE_OUTBOUND', 'PACKAGING_INBOUND', 'PACKAGING_ISSUE_OUTBOUND', 'ADJUSTMENT_POSITIVE', 'ADJUSTMENT_NEGATIVE', name='transactiontype'), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_bags', sa.Integer(), nullable=True),
    sa.Column('quantity_kip', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('quantity_units', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_line_id', sa.UUID(), nullable=True),
    sa.Column('lot_number', sa.String(length=20), nullable=True),
    sa.Column('count_value', sa.String(length=50), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('posted_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('direction IN (1, -1)', name='chk_direction'),
    sa.CheckConstraint('quantity_kg > 0', name='chk_qty_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['count_id'], ['count_catalog.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_st_balance_key', 'stock_transactions', ['company_id', 'warehouse_id', 'lot_id', 'count_id', 'owner_id'], unique=False)
    op.create_index('idx_st_pkg_balance', 'stock_transactions', ['company_id', 'warehouse_id', 'pkg_item_type'], unique=False)
    op.create_index('idx_st_reference', 'stock_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_st_transaction_date', 'stock_transactions', ['company_id', 'warehouse_id', 'transaction_date'], unique=False)
    op.create_index('idx_st_waste_balance', 'stock_transactions', ['company_id', 'warehouse_id', 'waste_type'], unique=False)
    op.create_index(op.f('ix_stock_transactions_transaction_date'), 'stock_transactions', ['transaction_date'], unique=False)
    op.create_table('user_company_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DIRECTOR', 'DEPUTY_DIRECTOR', 'WH_RAW', 'WH_FINISHED', 'PRODUCTION', 'ACCOUNTANT', name='userrole'), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company')
    )
    op.create_index(op.f('ix_user_company_roles_company_id'), 'user_company_roles', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_company_roles_user_id'), 'user_company_roles', ['user_id'], unique=False)
    op.create_table('daily_report_lines',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('line_category', sa.Enum('PRODUCTION_INBOUND', 'RECEIPT', 'PRODUCTION_ISSUE', 'SALE_OUTBOUND', 'PACKAGING_ISSUE', name='linecategory'), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('count_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('waste_type', sa.Enum('ST_3', 'ST_7_11', 'ST_1', 'ST_36', 'ST_98', 'MYCHKA', 'ROVNITSA', name='wastetype'), nullable=True),
    sa.Column('buyer_id', sa.UUID(), nullable=True),
    sa.Column('pkg_item_type', sa.Enum('BAG', 'CONE', 'PACKAGE', 'CORRUGATED_SHEET', 'PARAFFIN', 'BOX', name='packagingitemtype'), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_bags', sa.Integer(), nullable=True),
    sa.Column('quantity_kip', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('quantity_units', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_kg >= 0', name='chk_drl_qty'),
    sa.ForeignKeyConstraint(['buyer_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['count_id'], ['count_catalog.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_report_id', 'line_number', name='uq_drl_report_line')
    )
    op.create_index('idx_drl_report', 'daily_report_lines', ['daily_report_id'], unique=False)
    op.create_table('inventory_adjustment_lines',
    sa.Column('adjustment_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('count_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('waste_type', sa.Enum('ST_3', 'ST_7_11', 'ST_1', 'ST_36', 'ST_98', 'MYCHKA', 'ROVNITSA', name='wastetype'), nullable=True),
    sa.Column('pkg_item_type', sa.Enum('BAG', 'CONE', 'PACKAGE', 'CORRUGATED_SHEET', 'PARAFFIN', 'BOX', name='packagingitemtype'), nullable=True),
    sa.Column('quantity_kg_before', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_kg_after', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('bags_before', sa.Integer(), nullable=False),
    sa.Column('bags_after', sa.Integer(), nullable=False),
    sa.Column('units_before', sa.Integer(), nullable=False),
    sa.Column('units_after', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_id'], ['inventory_adjustments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['count_id'], ['count_catalog.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adjustment_id', 'line_number', name='uq_adj_line')
    )
    op.create_index(op.f('ix_inventory_adjustment_lines_adjustment_id'), 'inventory_adjustment_lines', ['adjustment_id'], unique=False)
    op.create_table('shipments',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('shipment_number', sa.String(length=25), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PARTIALLY_CANCELLED', 'CANCELLED', name='shipmentstatus'), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('daily_report_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'shipment_number', name='uq_shipment_company_number')
    )
    op.create_index(op.f('ix_shipments_buyer_id'), 'shipments', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_shipments_company_id'), 'shipments', ['company_id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_date'), 'shipments', ['shipment_date'], unique=False)
    op.create_index(op.f('ix_shipments_warehouse_id'), 'shipments', ['warehouse_id'], unique=False)
    op.create_table('shipment_lines',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('count_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_bags', sa.Integer(), nullable=True),
    sa.Column('cancelled_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('cancelled_bags', sa.Integer(), nullable=False),
    sa.Column('is_fully_cancelled', sa.Boolean(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_kg > 0', name='chk_sl_qty_positive'),
    sa.ForeignKeyConstraint(['count_id'], ['count_catalog.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'line_number', name='uq_sl_shipment_line')
    )
    op.create_index(op.f('ix_shipment_lines_shipment_id'), 'shipment_lines', ['shipment_id'], unique=False)
    op.create_table('shipment_cancellations',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('shipment_line_id', sa.UUID(), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_bags', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reversal_transaction_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity_kg > 0', name='chk_sc_qty_positive'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['shipment_line_id'], ['shipment_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_cancellations_shipment_id'), 'shipment_cancellations', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_cancellations_shipment_id'), table_name='shipment_cancellations')
    op.drop_table('shipment_cancellations')
    op.drop_index(op.f('ix_shipment_lines_shipment_id'), table_name='shipment_lines')
    op.drop_table('shipment_lines')
    op.drop_index(op.f('ix_shipments_warehouse_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_date'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_company_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_buyer_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_inventory_adjustment_lines_adjustment_id'), table_name='inventory_adjustment_lines')
    op.drop_table('inventory_adjustment_lines')
    op.drop_index('idx_drl_report', table_name='daily_report_lines')
    op.drop_table('daily_report_lines')
    op.drop_index(op.f('ix_user_company_roles_user_id'), table_name='user_company_roles')
    op.drop_index(op.f('ix_user_company_roles_company_id'), table_name='user_company_roles')
    op.drop_table('user_company_roles')
    op.drop_index(op.f('ix_stock_transactions_transaction_date'), table_name='stock_transactions')
    op.drop_index('idx_st_waste_balance', table_name='stock_transactions')
    op.drop_index('idx_st_transaction_date', table_name='stock_transactions')
    op.drop_index('idx_st_reference', table_name='stock_transactions')
    op.drop_index('idx_st_pkg_balance', table_name='stock_transactions')
    op.drop_index('idx_st_balance_key', table_name='stock_transactions')
    op.drop_table('stock_transactions')
    op.drop_index(op.f('ix_inventory_adjustments_warehouse_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_company_id'), table_name='inventory_adjustments')
    op.drop_table('inventory_adjustments')
    op.drop_index(op.f('ix_daily_reports_warehouse_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_company_id'), table_name='daily_reports')
    op.drop_index('idx_dr_warehouse_date', table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_counterparty_contacts_counterparty_id'), table_name='counterparty_contacts')
    op.drop_table('counterparty_contacts')
    op.drop_index(op.f('ix_contracts_counterparty_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_company_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_warehouses_company_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_table('shipment_number_sequences')
    op.drop_index(op.f('ix_lots_company_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_table('lot_number_sequences')
    op.drop_index(op.f('ix_counterparties_company_id'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index(op.f('ix_count_catalog_company_id'), table_name='count_catalog')
    op.drop_table('count_catalog')
    op.drop_table('adjustment_number_sequences')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_company_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
